apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: console
  name: console
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: console
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: console
    spec:
      containers:
        - args:
            - -c
            - echo "$(CONSOLE)_CONFIG_FILE" > /tmp/config.yml; /app/console
          command:
            - /bin/sh
          env:
            - name: CONFIG_FILEPATH
              value: /tmp/config.yml
            - name: CONSOLE_CONFIG_FILE
              value: |
                kafka:
                  brokers: ["redpanda-0:9092"]
                  schemaRegistry:
                    enabled: true
                    urls: ["http://redpanda-0:8081"]
                redpanda:
                  adminApi:
                    enabled: true
                    urls: ["http://redpanda-0:9644"]
          image: docker.redpanda.com/redpandadata/console:v2.6.1
          name: redpanda-console
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
