# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY producer.py .
COPY logging_config.py .
COPY admin.py .
COPY utils.py .
COPY requirements.txt .
COPY db/ db/

# Install any necessary dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Run producer.py when the container launches
CMD ["python", "producer.py"]