apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: redpanda-1
  name: redpanda-1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redpanda-1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: redpanda-1
    spec:
      containers:
        - args:
            - redpanda
            - start
            - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:29092
            - --advertise-kafka-addr internal://redpanda-1:9092,external://redpanda-1:29092
            - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:28082
            - --advertise-pandaproxy-addr internal://redpanda-1:8082,external://redpanda-1:28082
            - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:28081
            - --rpc-addr redpanda-1:33145
            - --advertise-rpc-addr redpanda-1:33145
            - --mode dev-container
            - --smp 1
            - --default-log-level=info
            - --seeds redpanda-0:33145
          image: docker.redpanda.com/redpandadata/redpanda:v24.1.12
          name: redpanda-1
          ports:
            - containerPort: 28081
              protocol: TCP
            - containerPort: 28082
              protocol: TCP
            - containerPort: 29092
              protocol: TCP
            - containerPort: 9644
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/redpanda/data
              name: redpanda-1
      restartPolicy: Always
      volumes:
        - name: redpanda-1
          persistentVolumeClaim:
            claimName: redpanda-1
