docker_build('producer', context='.', dockerfile='Dockerfile.producer')
docker_build('consumer', context='.', dockerfile='Dockerfile.consumer')

# docker_compose('docker-compose.yml')

k8s_yaml('./producer-deployment.yaml')
k8s_yaml('./consumer-deployment.yaml')
k8s_yaml('./redpanda-0-deployment.yaml')
k8s_yaml('./redpanda-1-deployment.yaml')
k8s_yaml('./redpanda-2-deployment.yaml')

k8s_yaml('./redpanda-0-service.yaml')
k8s_yaml('./redpanda-1-service.yaml')
k8s_yaml('./redpanda-2-service.yaml')

k8s_yaml('./redpanda-0-persistentvolumeclaim.yaml')
k8s_yaml('./redpanda-1-persistentvolumeclaim.yaml')
k8s_yaml('./redpanda-2-persistentvolumeclaim.yaml')